src/Entity/Lieu.php
<?php

namespace App\Entity;

use App\Repository\LieuRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LieuRepository::class)]
class Lieu
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $rue = null;

    #[ORM\Column]
    private ?float $latitude = null;

    #[ORM\Column]
    private ?float $longitude = null;

    #[ORM\ManyToOne(inversedBy: 'lieux')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Ville $ville = null;

    #[ORM\OneToMany(mappedBy: 'lieu', targetEntity: Sortie::class)]
    private Collection $lieu_sorties;

    public function __construct()
    {
        $this->lieu_sorties = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getRue(): ?string
    {
        return $this->rue;
    }

    public function setRue(string $rue): static
    {
        $this->rue = $rue;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(float $latitude): static
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(float $longitude): static
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getVille(): ?Ville
    {
        return $this->ville;
    }

    public function setVille(?Ville $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        // Récupérez le code postal à partir de l'objet Ville associé
        return $this->ville->getCodePostal();
    }

    /**
     * @return Collection<int, Sortie>
     */
    public function getLieuSorties(): Collection
    {
        return $this->lieu_sorties;
    }

    public function addLieuSorty(Sortie $lieuSorty): static
    {
        if (!$this->lieu_sorties->contains($lieuSorty)) {
            $this->lieu_sorties->add($lieuSorty);
            $lieuSorty->setLieu($this);
        }

        return $this;
    }

    public function removeLieuSorty(Sortie $lieuSorty): static
    {
        if ($this->lieu_sorties->removeElement($lieuSorty)) {
            // set the owning side to null (unless already changed)
            if ($lieuSorty->getLieu() === $this) {
                $lieuSorty->setLieu(null);
            }
        }

        return $this;
    }
}

src/Entity/Sortie.php
<?php

namespace App\Entity;

use App\Repository\SortieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SortieRepository::class)]
class Sortie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateHeureDebut = null;

    #[ORM\Column(nullable: true)]
    private ?int $duree = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateLimiteInscription = null;

    #[ORM\Column]
    private ?int $nbInscriptionsMax = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $infosSortie = null;

    #[ORM\ManyToOne(inversedBy: 'lieu_sorties')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Lieu $lieu = null;

    #[ORM\ManyToOne(inversedBy: 'sorties')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Campus $campus_sorties = null;

    #[ORM\ManyToOne(inversedBy: 'organisateur')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Participant $organisateur = null;

    #[ORM\ManyToMany(targetEntity: Participant::class, mappedBy: 'sorties')]
    private Collection $participants;

    #[ORM\ManyToOne(inversedBy: 'sorties')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Etat $sortie_etat = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $MotifAnnulation = null;

    public function __construct()
    {
        $this->participants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateHeureDebut(): ?\DateTimeInterface
    {
        return $this->dateHeureDebut;
    }

    public function setDateHeureDebut(\DateTimeInterface $dateHeureDebut): static
    {
        $this->dateHeureDebut = $dateHeureDebut;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(?int $duree): static
    {
        $this->duree = $duree;

        return $this;
    }

    public function getDateLimiteInscription(): ?\DateTimeInterface
    {
        return $this->dateLimiteInscription;
    }

    public function setDateLimiteInscription(\DateTimeInterface $dateLimiteInscription): static
    {
        $this->dateLimiteInscription = $dateLimiteInscription;

        return $this;
    }

    public function getNbInscriptionsMax(): ?int
    {
        return $this->nbInscriptionsMax;
    }

    public function setNbInscriptionsMax(int $nbInscriptionsMax): static
    {
        $this->nbInscriptionsMax = $nbInscriptionsMax;

        return $this;
    }

    public function getInfosSortie(): ?string
    {
        return $this->infosSortie;
    }

    public function setInfosSortie(?string $infosSortie): static
    {
        $this->infosSortie = $infosSortie;

        return $this;
    }

    public function getOrganisateur(): ?Participant
    {
        return $this->organisateur;
    }

    public function setOrganisateur(?Participant $organisateur): static
    {
        $this->organisateur = $organisateur;

        return $this;
    }

    /**
     * @return Collection<int, Participant>
     */
    public function getParticipants(): Collection
    {
        return $this->participants;
    }

    public function addParticipant(Participant $participant): static
    {
        if (!$this->participants->contains($participant)) {
            $this->participants->add($participant);
            $participant->addSorty($this);
        }

        return $this;
    }

    public function removeParticipant(Participant $participant): static
    {
        if ($this->participants->removeElement($participant)) {
            $participant->removeSorty($this);
        }

        return $this;
    }

    public function getLieu(): ?Lieu
    {
        return $this->lieu;
    }

    public function setLieu(?Lieu $lieu): static
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getCampusSorties(): ?Campus
    {
        return $this->campus_sorties;
    }

    public function setCampusSorties(?Campus $campus_sorties): static
    {
        $this->campus_sorties = $campus_sorties;

        return $this;
    }

    public function getSortieEtat(): ?Etat
    {
        return $this->sortie_etat;
    }

    public function setSortieEtat(?Etat $sortie_etat): static
    {
        $this->sortie_etat = $sortie_etat;

        return $this;
    }

    public function getMotifAnnulation(): ?string
    {
        return $this->MotifAnnulation;
    }

    public function setMotifAnnulation(?string $MotifAnnulation): static
    {
        $this->MotifAnnulation = $MotifAnnulation;

        return $this;
    }
}

src/Form/SortieType.php
<?php

namespace App\Form;

use App\Entity\Campus;
use App\Entity\Lieu;
use App\Entity\Sortie;
use App\Entity\Ville;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

class SortieType extends AbstractType
{
    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('dateHeureDebut', DateTimeType::class, [
                'html5' => true,
                'widget' => 'single_text'
            ])
            ->add('duree')
            ->add('dateLimiteInscription', DateType::class, [
                'html5' => true,
                'widget' => 'single_text'
            ])
            ->add('nbInscriptionsMax')
            ->add('infosSortie')

            ->add('rue', TextType::class, [
                'mapped' => false,
            ])
            ->add('longitude', TextType::class, [
                'mapped' => false,
            ])
            ->add('latitude', TextType::class, [
                'mapped' => false,
            ])
            ->add('codePostal', TextType::class, [
                'mapped' => false,])
            ->add('ville', EntityType::class, [
                'class' => Ville::class,
                'choice_label' => 'nom',
                'placeholder' => 'Sélectionnez une ville',
                'mapped' => false,
                'attr' => [
                    'data-ville-id' => 'ville',
                ],
            ])
            ->add('lieu', EntityType::class, [
                'class' => Lieu::class,
                'choice_label' => 'nom',
                'placeholder' => 'Sélectionnez un lieu',
                'attr' => [
                    'data-lieu-id' => 'lieu',
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Sortie::class,
        ]);
    }
}

templates/sortie/_form.html.twig
{{ form_start(form) }}

    {{ form_widget(form) }}

<button class="btn_creersortie2">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/sortie/accueil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sortie{% endblock %}

{% block body %}
    <div class="date">
        {{ "Date du jour : " ~ "now"|date('d/m/Y') }} {# bon à savoir le ~ permet de concaténer des chaînes de caractères #}
    </div>
    <br>
    <div class="user_connecté">
        {% if app.user %}
            Participant : {{ app.user.nom }} {{ app.user.prenom }}
        {% else %}
            Personne n'est connectée lol
        {% endif %}
    </div>
    <div class="filtres">
        <h2>Filtrer les sorties</h2>
        <form method="get" action="{{ path('app_sortie_accueil') }}">
            <div class="recherche_container">
                <div class="recherche_container2">
                    <div class="recherche_container3">
                        <div class="recherche_nom">
                            <p>Le nom de la sortie contient:</p>
                            <input type="text" name="search" id="recherche" placeholder="Rechercher par nom" value="{{ app.request.query.get('search') }}">
                        </div>
                        <div class="recherche_date">
                            <div class="form-group">
                                <label for="dateDebut">Entre le :</label>
                                <input type="date" name="dateDebut" id="dateDebut" value="{{ app.request.query.get('dateDebut') }}">
                            </div>
                            <div class="form-group">
                                <label for="dateFin">et le :</label>
                                <input type="date" name="dateFin" id="dateFin" value="{{ app.request.query.get('dateFin') }}">
                            </div>
                        </div>
                    </div>

                    <div class="checkbox_option">
                        <label class="label_checkbox">
                            <input type="checkbox" name="organisateur" value="1" {% if app.request.query.get('organisateur') == '1' %}checked{% endif %}>
                            Sortie dont je suis l'organisateur/trice
                        </label>
                        <label class="label_checkbox">
                            <input type="checkbox" name="inscrit" value="1" {% if app.request.query.get('inscrit') == '1' %}checked{% endif %}>
                            Sortie auxquelles je suis inscrit/e
                        </label>
                        <label class="label_checkbox">
                            <input type="checkbox" name="non_inscrit" value="1" {% if app.request.query.get('non_inscrit') == '1' %}checked{% endif %}>
                            Sortie auxquelles je ne suis pas inscrit/e
                        </label>
                        <label class="label_checkbox">
                            <input type="checkbox" name="passees" value="1" {% if app.request.query.get('passees') == '1' %}checked{% endif %}>
                            Sorties passées
                        </label>
                    </div>
                </div>

                <div class="btn_recherche">
                    <button type="submit" id="rechercher-button" class="btn">Rechercher</button>
                </div>
            </div>
        </form>
    </div>

    <br>
    <div class="parent-categories-list">
        <section class="categories-list">
            <table class="table">
                <thead>
                    <tr>
                        <th>Nom de la sortie</th>
                        <th>Date de la sortie</th>
                        <th>Clôture</th>
                        <th>Inscrits/places</th>
                        <th>État</th>
                        <th>Organisateur</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for sortie in sorties %}
                        <tr>
                            <td>{{ sortie.nom }}</td>
                            <td>{{ sortie.dateHeureDebut ? sortie.dateHeureDebut|date('d/m/y H:i') : '' }} h</td>
                            <td>{{ sortie.dateLimiteInscription ? sortie.dateLimiteInscription|date('d/m/y') : '' }}</td>
                            <!-- suivi du nombre maximum d'inscriptions / participants et un maximum  -->
                            <td>{{ sortie.participants|length }} / {{ sortie.nbInscriptionsMax }}</td>
                            <td>{{ sortie.sortieEtat.libelle }}</td>
                            <td><a href="{{ path('app_participant_show', {'id': sortie.organisateur.id}) }}"> {{ sortie.organisateur.nom|upper }} {{ sortie.organisateur.prenom|capitalize }}</td>
                            <td>
                                <a href="{{ path('app_sortie_details', {'id': sortie.id}) }}">Afficher</a>
                                /
                                <a href="{{ path('app_sortie_modification', {'id': sortie.id}) }}">Modifier</a>
                                /
                                <a href="{{ path('app_sortie_annulation', {'id': sortie.id}) }}">Annuler</a>
                                /
                                <a href="{{ path('app_sortie_inscription', {'id': sortie.id}) }}">s'inscrire</a>
                                /
                                <a href="{{ path('app_sortie_desister', {'id': sortie.id}) }}">se désister</a>

                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="8">Pas de sortie trouvée</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </section>
        <br>
    </div>

    <div>
        <a href="{{ path('app_sortie_creersortie') }}" class="btn_creersortie2 ">Créer une sortie</a>
    </div>
    <br>
<div>
<p></p>
    <p></p>
    <p></p>
</div>
{% endblock %}

templates/sortie/annulation.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1 class="h1_creerSortie">Annuler une sortie</h1>

    <div class="table-container">
        <table class="table_annulation">
            <tbody>
                <tr>
                    <th>Nom de la sortie</th>
                    <td>{{ sortie.nom }}</td>
                </tr>
                <tr>
                    <th>Date de la sortie</th>
                    <td>{{ sortie.dateHeureDebut ? sortie.dateHeureDebut|date('d/m/y H:i') : '' }}</td>
                </tr>
                <tr>
                    <th>Campus</th>
                    <td>{{ sortie.campusSorties.nom }}</td>
                </tr>
                <tr>
                    <th>Lieu</th>
                    <td>{{ sortie.lieu.nom }}</td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="form-container3">
        {{ form_start(form) }}

        <div class="motif-container">
            {{ form_label(form.motifAnnulation, 'Motif d\'annulation') }}
            {{ form_widget(form.motifAnnulation) }}
        </div>


        <div class="btn_creersortie">
            <a href="{{ path('app_sortie_accueil', {'id': sortie.id}) }}" class="btn">Retour accueil</a>
            <button type="submit" class="btn">Annuler la sortie</button>
        </div>
        {{ form_end(form) }}
    </div>
{% endblock %}

{% block title %}

{% endblock %}

templates/sortie/creer_sortie.html.twig
{% extends 'base.html.twig' %}

{% block title %}Création de Sortie{% endblock %}

{% block body %}
    <h1 class="h1_creerSortie">Créer une nouvelle Sortie</h1>

    <div class="form-container-creerSortie">
        <div class="column-creerSortie">
            {{ form_start(form) }}
            <div class="creation_sortie">
                {{ form_label(form.nom) }}
                {{ form_widget(form.nom) }}
            </div>
            <div class="creation_sortie">
                {{ form_label(form.dateHeureDebut) }}
                {{ form_widget(form.dateHeureDebut) }}
            </div>
            <div class="creation_sortie">
                {{ form_label(form.dateLimiteInscription) }}
                {{ form_widget(form.dateLimiteInscription) }}
            </div>
            <div class="creation_sortie">
                {{ form_label(form.nbInscriptionsMax) }}
                {{ form_widget(form.nbInscriptionsMax) }}
            </div>
            <div class="creation_sortie">
                {{ form_label(form.duree) }}
                {{ form_widget(form.duree) }}
            </div>
            <div class="creation_sortie">
                {{ form_label(form.infosSortie) }}
                {{ form_widget(form.infosSortie) }}
            </div>
        </div>
        <div class="column-creerSortie2">
            <div class="creation_sortie">
                <label>Campus: </label>
                {{ participant.campus.nom }}
            </div>
            <div class="creation_sortie">
                {{ form_label(form.ville) }}
                {{ form_widget(form.ville) }}
            </div>
            <div class="creation_sortie">
                {{ form_label(form.lieu) }}
                {{ form_widget(form.lieu) }}
                <button type="button" id="ajout_lieu_button">+</button>
            </div>
            <div class="creation_sortie">
                {{ form_label(form.rue) }}
                {{ form_widget(form.rue) }}
            </div>
            <div class="creation_sortie">
                {{ form_label(form.codePostal) }}
                {{ form_widget(form.codePostal) }}
            </div>
            <div class="creation_sortie">
                {{ form_label(form.longitude) }}
                {{ form_widget(form.longitude) }}
            </div>
            <div class="creation_sortie">
                {{ form_label(form.latitude) }}
                {{ form_widget(form.latitude) }}
            </div>
        </div>
    </div>
    <div class="btn_creersortie">
        <button type="submit" name="action" value="enregistrer" class="btn_creersortie2">Enregistrer</button>
        <button type="submit" name="action" value="publier" class="btn_creersortie2">Publier la sortie</button>
        <a href="{{ path('app_sortie_accueil') }}" class="btn_creersortie2">Annuler</a>
    </div>
    {{ form_end(form) }}

    <<div id="location-popup" style="display: none;">
    <div id="popup-content">
        {{ form_start(lieuForm, {'attr': {'id': 'lieu-form'}}) }}
        {{ form_widget(lieuForm) }}
        <button type="submit" class="btn">Créer Lieu</button>
        <button id="close-popup-button" class="btn">Fermer</button>
        {{ form_end(lieuForm) }}
    </div>
</div>
    <script src="{{ asset('assets/autocomplete_lieu.js') }}"></script>
    <script src="{{ asset('assets/ajout_lieu_popup.js') }}"></script>
{% endblock %}

templates/sortie/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}Informations d'une Sortie{% endblock %}

{% block body %}

    <h1 class="h1">Afficher une sortie</h1>
    <div class="colonnes">
        <div class="colonne1">
            <div class="p_sortie">
                <p class="p_style">Nom de la sortie:</p>
                <p>{{ sortie.nom }}</p>
            </div>
            <div class="p_sortie">
                <p class="p_style">Date et heure de la sortie:</p>
                <p>{{ sortie.dateHeureDebut ? sortie.dateHeureDebut|date('d/m/y H:i') : '' }} h</p>
            </div>
            <div class="p_sortie">
                <p class="p_style">Date limite d'inscription: </p>
                <p>{{ sortie.dateLimiteInscription ? sortie.dateLimiteInscription|date('d/m/y') : '' }}</p>
            </div>
            <div class="p_sortie">
                <p class="p_style">Nombre de places: </p>
                <p>{{ sortie.nbInscriptionsMax }}</p>
            </div>
            <div class="p_sortie">
                <p class="p_style">Duree: </p>
                <p>{{ sortie.duree }} minutes</p>
            </div>
            <div class="p_sortie">
                <p class="p_style">Description et infos: </p>
                <p>{{ sortie.infosSortie }}</p>
            </div>
            {% if sortie.motifAnnulation %}
                <div class="p_sortie">
                    <p class="p_style">Motif d'annulation: </p>
                    <p>{{ sortie.motifAnnulation }}</p>
                </div>
            {% endif %}
        </div>
        <div class="colonne1">
            <div class="p_sortie">
                <p class="p_style">Campus: </p>
                <p>{{ sortie.campusSorties.nom }}</p>
            </div>
            <div class="p_sortie">
                <p class="p_style">Lieu: </p>
                <p>{{ sortie.lieu.nom }}</p>
            </div>
            <div class="p_sortie">
                <p class="p_style">Rue: </p>
                <p>{{ sortie.lieu.rue }}</p>
            </div>
            <div class="p_sortie">
                <p class="p_style">Code postal: </p>
                <p>{{ sortie.lieu.ville.codePostal }}</p>
            </div>
            <div class="p_sortie">
                <p class="p_style">Latitude: </p>
                <p>{{ sortie.lieu.latitude }}</p>
            </div>
            <div class="p_sortie">
                <p class="p_style">Longitude: </p>
                <p>{{ sortie.lieu.longitude }}</p>
            </div>
        </div>
    </div>

    <section class="participants">
        <h2>Liste des participants inscrits: </h2>
        <table class="tab_sortie">
            <tr>
                <th>Pseudo</th>
                <th>Nom</th>
            </tr>
            {% for participant in sortie.participants %}
                <tr>
                    <td>{{ participant.pseudo }}</td>
                    <td>{{ participant.nom }} {{ participant.prenom }}</td>
                </tr>
            {% endfor %}
        </table>
    </section>
{% endblock %}

templates/sortie/modification.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification d'une Sortie{% endblock %}

{% block body %}
    <h1 class="h1_creerSortie">Modifier une sortie</h1>

    {{ form_start(form) }}

    <div class="form-container-creerSortie">
        <div class="column-creerSortie">
            {{ form_start(form) }}

            <div class="creation_sortie">
                {{ form_label(form.nom) }}
                {{ form_widget(form.nom) }}
            </div>
            <div class="creation_sortie">
                {{ form_label(form.dateHeureDebut) }}
                {{ form_widget(form.dateHeureDebut) }}
            </div>
            <div class="creation_sortie">
                {{ form_label(form.dateLimiteInscription) }}
                {{ form_widget(form.dateLimiteInscription) }}
            </div>
            <div class="creation_sortie">
                {{ form_label(form.nbInscriptionsMax) }}
                {{ form_widget(form.nbInscriptionsMax) }}
            </div>
            <div class="creation_sortie">
                {{ form_label(form.duree) }}
                {{ form_widget(form.duree) }}
            </div>
            <div class="creation_sortie">
                {{ form_label(form.infosSortie) }}
                {{ form_widget(form.infosSortie) }}
            </div>
        </div>

        <div class="column-creerSortie2">
            <div class="creation_sortie">
                {{ form_label(form.ville) }}
                {{ form_widget(form.ville) }}
            </div>
            <div class="creation_sortie">
                {{ form_label(form.lieu) }}
                {{ form_widget(form.lieu) }}
            </div>
            <div class="creation_sortie">
                {{ form_label(form.rue) }}
                {{ form_widget(form.rue) }}
            </div>
            <div class="creation_sortie">
                {{ form_label(form.codePostal) }}
                {{ form_widget(form.codePostal) }}
            </div>
            <div class="creation_sortie">
                {{ form_label(form.longitude) }}
                {{ form_widget(form.longitude) }}
            </div>
            <div class="creation_sortie">
                {{ form_label(form.latitude) }}
                {{ form_widget(form.latitude) }}
            </div>
        </div>
    </div>

    <div class="btn_creersortie">
        <button class="btn_creersortie2">{{ button_label|default('Enregistrer') }}</button>
        {{ form_end(form) }}

        <a href="{{ path('app_sortie_accueil') }}" class="btn_creersortie2">Accueil</a>
    </div>

        <div class="btn_supprimer_sortie">
            {{ include('sortie/supprimer_sortie.html.twig') }}
        </div>

    <script src="{{ asset('assets/autocomplete_lieu.js') }}"></script>
{% endblock %}

templates/sortie/supprimer_sortie.html.twig
<form method="post" action="{{ path('app_sortie_supprimer', {'id': sortie.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cette sortie ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ sortie.id) }}">
    <button class="btn_supprimer_sortie2">Supprimer</button>
</form>